### ISSUE TITLE
Is it possible for this application to return to intuitive 1-plane drawing?

### ISSUE THREAD

**Issue by lichengzhang1** [seemanne/1PlanarTester#1]
Hello, I'm working on 1-planar graphs as well.  And when I saw this, I thought it was great, since  sometimes I want to verify whether a  graph with small vertices is a 1-planar graph. I'm interested if this programme could be explained more clearly.  For example, if a graph G is not a 1-planar graph, then your  program produces "false:“ and If not, then a 1-planar drawing is returned (or even an intuitively drawn graph).

**Comment by seemanne** [comment]
Hello, at the moment, the program will return a plane drawing of the planarization (Gstar) if you call it with verbose = True, using the drawing implementation provided by [NetworkX](https://networkx.org/documentation/stable/reference/generated/networkx.drawing.nx_pylab.draw_planar.html). You can call createLog to generate a list indicating which vertex of the planarization corresponds to a crossing of the 1-plane drawing. Does this answer your question?

**Comment by lichengzhang1** [comment]
Thank you very much for your response. I completed the test case successfully. Another interesting question is: how fast this programme is? The test graph on 8 vertices looks good and should take less than a minute.

```
adjacency_dict = {
0: (1, 2, 3, 4, 5, 6, 7),
1: (0, 2, 3, 4, 5, 6),
2: (0, 1, 3),
3: (0, 1, 2, 4, 5, 7),
4: (0, 1, 3, 5, 6, 7),
5: (0, 1, 3, 4, 6, 7),
6: (0, 1, 4, 5, 7),
7: (0, 3, 4, 5, 6)}
G = nx.Graph(adjacency_dict)
E = generateE(G)
x ,y = searchTree([],G, E, verbose = True)
print(x)

s=createLog(x,y,E,8)
print(s)
```


```
Crossings in order: 
Vertex  8  represents the crossing  [[0 4]
 [3 7]]
Vertex  9  represents the crossing  [[0 5]
 [1 6]]
Vertex  10  represents the crossing  [[1 4]
 [3 5]]
Vertex  11  represents the crossing  [[4 6]
 [5 7]]
```
![image](https://user-images.githubusercontent.com/82444903/170687718-2777b2e9-d293-4e91-a854-33807ad3348b.png)

**Comment by seemanne** [comment]
As you probably know 1-planarity testing is NP-Hard, so I wouldn't expect much for larger instances, but a reasonable bound is that the algorithm does around $$O(2^{(m^2 + m - n - \sum deg(v_i)^2)/2})$$ operations in the worst case (with n being the number of vertices and m being the number of edges). The paper by Binucci et al. further suggests that instances with more than 30 vertices are increasingly unsolvable in reasonable time. Hope this helps.

**Comment by lichengzhang1** [comment]
I am quite appreciative of your prompt response. Yean, I'm aware that the 1-planarity testing  and  computing crossing number both fall into the NP-Hard category. But I think it's sstill really commendable if we can test 1-planarity  on graphs with less than 20 vertices.  Because we don't know enough about the 1-planarity of graph classes, even when there are only a few vertices. As for graph on n vertices, I know that 1-planarity on graphs  with less than or equal to seven vertices  are fully characterized.  

- Vladimir P. Korzhik, Minimal non-1-planar graphs, Discrete Mathematics, Volume 308, Issue 7, 2008, Pages 1319-1327,
https://doi.org/10.1016/j.disc.2007.04.009.
